//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tusimaka
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyBestillinger
    {
        public int Id { get; set; }
        public int KundeId { get; set; }
        public int StrekningsId { get; set; }
        public int AntallPersoner { get; set; }
        public Nullable<int> ReturId { get; set; }
    }
}
